###########################
## Replant Configuration ##
###########################

 crops:
   - Crops
   - Carrot
   - Potato
   - Cocoa
   - Nether_Warts

 replace-delay: 100
   
 immature-crops: false
 
 default: true
