###########################
## Replant Configuration ##
###########################

 crops:
   - Crops
   - Carrot
   - Potato
   - Cocoa
   - Nether_Warts

 replace-delay: 50
   
 immature-crops: false
 
 default: true
 
 forced-regions:
   - spawn
   - jail
