###########################
## Replant Configuration ##
###########################

 enabled: true

 crops:
   - Wheat
   - Carrot
   - Potato
   - Nether_Wart
   - Nether_Stalk

 
   
 immature-crops: false
 
 default: true
