###########################
## Replant Configuration ##
###########################

 crops:
   - Wheat
   - Carrot
   - Potato
   - Nether_Wart
   - Nether_Stalk

 replace-delay: 100
   
 immature-crops: false
 
 default: true
